apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672 # AMQP port
            - containerPort: 15672 # Web UI port
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest" # Replace with a secure username
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest" # Replace with a secure password
