apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672 # AMQP port
            - containerPort: 15672 # Web UI port
          env:
            - name: RABBITMQ_USERNAME
              value: "user" # RabbitMQ username
            - name: RABBITMQ_PASSWORD
              value: "password" # RabbitMQ password
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/" # Default virtual host
