apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672 # Exposing the AMQP port
      targetPort: 5672
    - name: managment
      protocol: TCP
      port: 15672 # Exposing the web UI port
      targetPort: 15672
      nodePort: 30001 # Exposing the web UI on a NodePort (accessible from outside the cluster)
  type: NodePort
